language: python
dist: trusty
services:
  - docker

before_install:
  - docker pull python:2.7

jobs:
  include:
    - stage: lint
      script: docker run -e TRAVIS_CI=1 -ti -v $PWD:/src python:2.7 /src/_CI/scripts/lint
    - stage: test
      script: docker run -e TRAVIS_CI=1 -ti -v $PWD:/src python:2.7 /src//_CI/scripts/test
    - stage: build
      script: docker run -e TRAVIS_CI=1 -ti -v $PWD:/src python:2.7 /src//_CI/scripts/build
    - stage: upload
      script: docker run -e TRAVIS_CI=1 -ti -v $PWD:/src python:2.7 /src//_CI/scripts/upload
