language: python
dist: trusty
cache: pip

jobs:
  include:
    - stage: lint
      script: ./_CI/scripts/lint
    - stage: test
      script: ./_CI/scripts/test
    - stage: build
      script: ./_CI/scripts/build
    - stage: upload
      on:
        tags: true
        branch: master
      script: ./_CI/scripts/upload
