language: python
dist: trusty
cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements/development.txt
  - pip install -r requirements/documentation.txt
  - pip install -r requirements/testing.txt

jobs:
  include:
    - stage: lint
      script: ./_CI/scripts/lint
    - stage: test
      script: ./_CI/scripts/test
    - stage: build
      script: ./_CI/scripts/build
    - stage: upload
      on:
        # tags: true
        branch: master
      script: ./_CI/scripts/upload
